[package]
name = "sam_rust_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"peg" = "0.8.0"
write_x86_64 = {git = "https://github.com/samsa1/write_x86_64"}
